version: "3.7"
services:

  dbt:
    image: python:3.8.5
    environment:
      - GOOGLE_CLOUD_PROJECT
      - POSTGRES_HOST=postgres
    entrypoint: "${RUN_SCRIPT} ${TARGET}"
    working_dir: /repo
    volumes:
        - ".:/repo"
    depends_on:
      - postgres
      
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"